# Site settings
title: Hyemingway Blog
SEOTitle: Hyemin Ha
header-img: img/home-bg.jpg
email: hyeminh19@gmail.com
description: "Hello this is Hyemin from Korea, 안녕하세요! 하혜민의 블로그 입니다. "
keyword: "Web, JavaScript, Spring, HTML5, Python"
url: "https://hyemingway33.github.io" 
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true
